### ISSUE TITLE
Rename this repo to `tornado-deploy`

### ISSUE THREAD

**Issue by masih** [filecoin-project/tornado-deploy#71]
Since this repo is no longer used to deploy `autoretireve` and contains tornado related services, would it make sense to rename it to something like `tornado-deploy`?

Further, the `namespace` should also be renamed to `tornado` along with other traces of the name `autoretrieve`.

**Comment by kylehuntsman** [comment]
YES PLEASE. We've talked about this internally before and I think we're all aligned on `tornado-deploy`. The namespace being named `tornado` would probably also be fine.

**Comment by kylehuntsman** [comment]
@masih Correct me if I'm wrong, but changing the namespace wouldn't be a downtime event, but moreso a pod reschedule? I'd be down to take this on if I had some guidance.

**Comment by masih** [comment]
I think downtime in order of seconds is acceptable? if not we can do it with zero downtime, where we run two event reocorders: one in existing namespace and one in a new one. Then switch the DNS, wait for DNS records to expire and nuke the old one.

**Comment by willscott** [comment]
If it takes a few seconds that's fine imo

**Comment by masih** [comment]
Nice work @kylehuntsman  🙌
